edc_audit/urls.py
# from django.conf.urls import patterns, url
#
# from edc_audit import audit_trail_view
# # from edc.edc_audit.views.audit_trail_view import AuditTrailView
#
#
# urlpatterns = patterns('',
#     url(r'^(?P<section_name>\w+)/(?P<app_label>\w+)/(?P<model_name>\w+)/(?P<dashboard_type>\w+)/(?P<audit_subject_identifier>[\w\-]+)/(?P<audit_id>[\w]{8}-[\w]{4}-[\w]{4}-[\w]{4}-[\w]{12})/(?P<visit_code>\w+)/(?P<visit_instance>\w+)/$',
#     audit_trail_view,
#     name="audit_trail_url"
#     ),
# )

edc_audit/models.py
from django.db import models

from edc_base.model.models import BaseUuidModel


class AuditComment (BaseUuidModel):

    app_label = models.CharField(
        max_length=35,
    )

    model_name = models.CharField(
        max_length=50,
    )

    audit_subject_identifier = models.CharField(
        max_length=50,
    )

    audit_id = models.CharField(max_length=50)

    audit_code = models.CharField(
        max_length=25,
    )

    audit_comment = models.TextField(
        max_length=250,
        help_text='Add a comment describing the reason for the data change.'
    )

    def __unicode__(self):
        return self.audit_comment[0:50]

    class Meta:
        app_label = 'edc_audit'
        ordering = ['created']

edc_audit/templates/audit_comment_include.html
<table> 
<thead>
<th></th>
<th>#</th>
<th>created</th>
<th>modified</th>
<th>user</th>
<th>user modified</th>
<th>comment</th>
</thead>
<tbody>
{% for audit_comment in audit_comments %}   
    <tr>
    <td><A href="/admin/audit_trail/auditcomment/{{ audit_comment.pk }}/?next=audit_trail_url&app_label={{audit_comment.app_label}}&model_name={{audit_comment.model_name}}&audit_subject_identifier={{audit_comment.audit_subject_identifier}}&audit_id={{audit_comment.audit_id}}&visit_code={{ visit_code }}&visit_instance={{ visit_instance }}&dashboard_type={{ dashboard_type }}">edit</td>    
    <td>{{ audit_comment.audit_id }}</td>
    <td>{{ audit_comment.created }}</td>
    <td>{{ audit_comment.modified }}</td>
    <td>{{ audit_comment.user }}</td>
    <td>{{ audit_comment.user_modified }}</td>                            
    <td>{{ audit_comment }}</td>
    </tr>
{% endfor %}                    
</tbody>
</table>

edc_audit/templates/audit_trail.html
{% extends "base_audit_trail.html"%}
{% load friendly_load %}

{% friendly_load crypto_tags %}
{% ifnot_has_tag encrypted%}
    {% load dummy_encrypted %}
{% endifnot_has_tag %}

{% load common_tags %}

{% block app_labels %}
    {% include 'list_apps.html' %}
{% endblock %}

{% block model_names %}
    {% include 'list_models.html' %}
{% endblock %} 

{% block model_select_form %}
    {% include 'selector_form.html' %}
{% endblock%}

{% block audit_subject_identifier_form %}
    {% include 'audit_trail_form.html' %}
{% endblock%}

{% block history %}

    {% if not display_rows%}

        <p><i>{{ status_message }}</i> </p>

    {% else %}    

        {% if audit_comments %}
            <p><A href="#audit_comments"><small>jump to comments</small></A></p>
        {% endif %}

        <table> 
        <thead>
        <th>#</th>
        <th>comment</th> 
        {% for field_label in field_labels %}   
        <th>{{ field_label }}</th>
        {% endfor %}
        </thead>
        <tbody>
        {% for row in display_rows %}
            <tr><td>{{ forloop.counter }}</td>
            {% for r in row %} 
                {% if forloop.counter == 1 %}
                    <td><A href="/admin/audit_trail/auditcomment/{{r}}/?next=audit_trail_url&app_label={{app_label}}&model_name={{model_name}}&audit_subject_identifier={{audit_subject_identifier}}&audit_id={{row.1}}&visit_code={{ visit_code }}&visit_instance={{ visit_instance }}&dashboard_type={{ dashboard_type }}">{% if r == 'add'%}add{% else %}edit{% endif %}</td>
                {% else %}
                <td>{{ r|encrypted }}</td>
                {% endif %}
            {% endfor %} 
            </tr>                
        {% endfor %}     
        </tbody>
        </table>

        {% if audit_comments %}
            <H4><A name="audit_comments">Comments logged for {{ audit_subject_identifier }}</H4>
             {% include 'audit_comment_include.html' %}
        {% endif %}
    
    {% endif %}
    
{% endblock %}

edc_audit/templates/audit_trail_form.html
<form action="." method="POST">
<div style='display:none'>  
  {% csrf_token %}
</div>
<table>
<tr>
<td class="field">
    {{ form.app_label.errors }}
    <label for="id_app_label">App_label</label>
    {{ form.app_label }}
</td>
<td class="field">
    {{ form.model_name.errors }}
    <label for="id_model_name">Model Name</label>
    {{ form.model_name }}
</td>
<td class="field">
    {{ form.audit_subject_identifier.errors }}
    <label for="id_audit_subject_identifier">Subject Identifier</label>
    {{ form.audit_subject_identifier }}
</td>
<td>
    <input type="hidden" name="back_url_name" id="back_url_name" value="{{ back_url_name }}">
    <input type="hidden" name="dashboard_type" id="dashboard_type" value="{{ dashboard_type }}">
    <input type="hidden" name="visit_code" id="visit_code" value="{{ visit_code }}">
    <input type="hidden" name="visit_instance" id="visit_instance" value="{{ visit_instance }}">        
    <input type="submit" value="Search" class="default" name="submit" />
</td>

<script type="text/javascript">document.getElementById("id_audit_subject_identifier").focus();</script>
<script type="text/javascript">
    (function($) {
        var field = null;
    })(django.jQuery);
</script>
    </table>
</form>

edc_audit/templates/base_audit_trail.html
{% extends "section.html"%}
{% load common_tags %}

{% block section_links%}

{% if back_url_name = 'dashboard_url' and audit_subject_identifier %}
Back to <A href="{% url 'dashboard_url' subject_identifier=audit_subject_identifier dashboard_type=dashboard_type%}">dashboard for {{audit_subject_identifier }} </A>
{% endif %}

{% if back_url_name = 'dashboard_visit_url' and audit_subject_identifier %}
Back to <A href="{% url dashboard_visit_url subject_identifier=audit_subject_identifier dashboard_type=dashboard_type visit_code=visit_code visit_instance=visit_instance %}">dashboard for {{audit_subject_identifier }} </A>
{% endif %}


<h5>Audit Trail:  {{ app_label }} {{ verbose_name }}</h5>
{% include 'selector_buttons.html' %}
{% block model_select_form %}{% endblock%}
{% block audit_subject_identifier_form %}{% endblock%}


<font color="red">{{ err_message }}</font>

{% block app_labels %}{% endblock %}
{% block model_names %}{% endblock %}
{% block history %}{% endblock %}
{% endblock %}

edc_audit/templates/section_audit_trail.html
{% extends "base_audit_trail.html"%}
{% load friendly_load %}

{% friendly_load crypto_tags %}
{% ifnot_has_tag encrypted%}
    {% load dummy_encrypted %}
{% endifnot_has_tag %}

{% load common_tags %}

{% block app_labels %}
    {% include 'list_apps.html' %}
{% endblock %}

{% block model_names %}
    {% include 'list_models.html' %}
{% endblock %} 

{% block model_select_form %}
    {% include 'selector_form.html' %}
{% endblock%}

{% block audit_subject_identifier_form %}
    {% include 'audit_trail_form.html' %}
{% endblock%}

{% block history %}

    {% if not display_rows%}

        <p><i>{{ status_message }}</i> </p>

    {% else %}    

        {% if audit_comments %}
            <p><A href="#audit_comments"><small>jump to comments</small></A></p>
        {% endif %}

        <table> 
        <thead>
        <th>#</th>
        <th>comment</th> 
        {% for field_label in field_labels %}   
        <th>{{ field_label }}</th>
        {% endfor %}
        </thead>
        <tbody>
        {% for row in display_rows %}
            <tr><td>{{ forloop.counter }}</td>
            {% for r in row %} 
                {% if forloop.counter == 1 %}
                    <td><A href="/admin/audit_trail/auditcomment/{{r}}/?next=audit_trail_url&app_label={{app_label}}&model_name={{model_name}}&audit_subject_identifier={{audit_subject_identifier}}&audit_id={{row.1}}&visit_code={{ visit_code }}&visit_instance={{ visit_instance }}&dashboard_type={{ dashboard_type }}">{% if r == 'add'%}add{% else %}edit{% endif %}</td>
                {% else %}
                <td>{{ r|encrypted }}</td>
                {% endif %}
            {% endfor %} 
            </tr>                
        {% endfor %}     
        </tbody>
        </table>

        {% if audit_comments %}
            <H4><A name="audit_comments">Comments logged for {{ audit_subject_identifier }}</H4>
             {% include 'audit_comment_include.html' %}
        {% endif %}
    
    {% endif %}
    
{% endblock %}